version: '3'

services:
  yourls:
    image: yourls
    restart: always
    ports:
      - '80:80'
      - '443:443'
    environment:
      YOURLS_SITE: http://YOURLS_SITE
      YOURLS_USER: admin
      YOURLS_PASS: PASSWORD
      YOURLS_DB_PASS: DB_PASSWORD

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
