version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web:/web
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs/fullchain.pem:/certs/fullchain.pem
      - ./certs/privkey.pem:/certs/privkey.pem
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./web:/web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: DATABASE
      MYSQL_USER: USER
      MYSQL_PASSWORD: PASSWORD
    volumes:
      - ./mysql:/var/lib/mysql
